require 'eventmachine'
require 'escape_utils'
require 'addressable/uri'
require 'http/parser'

require 'base64'
require 'socket'

require 'em-http/core_ext/bytesize'
require 'em-http/http_header'
require 'em-http/http_encoding'
require 'em-http/http_options'
require 'em-http/client'
require 'em-http/multi'
require 'em-http/request'
require 'em-http/decoders'
require 'em-http/mock'