name: CI
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  spec:
    name: "RSpec / Ruby ${{ matrix.ruby }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: ["2.3", "2.4", "2.5", "2.6", "2.7", "3.0", "3.1", "3.2", "3.3"]
    steps:
      - run: sudo apt-get install libcurl4-openssl-dev
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - run: bundle exec rake spec
  spec-legacy:
    name: "RSpec / Ruby 2.2"
    runs-on: ubuntu-20.04
    steps:
      - run: sudo apt-get install libcurl4-openssl-dev
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.2
          bundler-cache: true
      - name: rake spec
        run: bundle exec rake spec
